INSERT INTO public.pokemon (nom_pokemon_fr,gif,img_type1,img_type2,dimension_gif,sprite,lien,est_ou,description,tier,classement) VALUES
	 ('Scalpereur','images/pokemon/scalpereur.gif','images/types/acier.png','images/types/tenebres.png','wider_longer_gif','images/sprites/sprite-kingambit.png','https://www.smogon.com/dex/sv/pokemon/kingambit/',true,'Scalpereur est sans aucun doute le Pokémon le plus menaçant du format, son talent Général Suprême augmente la puissance de ses attaques chaque fois qu''un allié est mis KO ce qui lui permet en fin de partie de menacer d''un Sweep à l''aide de sa priorité Coup Bas, son Coverage et le Teracristal.',0,2),
	 ('Ire-Foudre','images/pokemon/ire-foudre.gif','images/types/electrik.png','images/types/dragon.png','longer_gif','images/sprites/sprite-raging_bolt.png','https://www.smogon.com/dex/sv/pokemon/raging-bolt/',true,'L''intérêt d''Ire-Foudre réside dans sa capacité signature Vif Éclair qui est l''équivalent spécial d''un Coup Bas de type Type Électrik.',0,4),
	 ('Fort-Ivoire','images/pokemon/fort-ivoire.gif','images/types/sol.png','images/types/combat.png','wider_gif','images/sprites/sprite-great_tusk.png','https://www.smogon.com/dex/sv/pokemon/great-tusk/',true,'La présence de Fort-Ivoire dans le Metagame actuel est capitale afin d''offrir aux équipes un moyen de contrôler la présence des Hazards et de temporiser Scalpereur.  En dehors de Tour Rapide, son accès à Sabotage et Piège de Roc permet de garantir un progrès dans chaque partie en retirant les objets adverses et infligeant des dégâts résiduels. Autrement, Fort-Ivoire est du fait de son double type et de ses statistiques une excellente réponse à la plupart des menaces physiques du tier et s''intègrera parfaitement dans la majorité des équipes.',0,1),
	 ('Miascarade','images/pokemon/miascarade.gif','images/types/plante.png','images/types/tenebres.png','longer_gif','images/sprites/sprite-miascarade.png','https://www.smogon.com/dex/sv/pokemon/meowscarada/',true,'Doté d''une bonne Vitesse et de Sabotage, Miascarade est un bon pivot en OverUsed. Si son coverage n''est pas excellent, il est suffisant grâce au boost donné par Protéen. Avec un coup critique assuré, Magie Florale est une bonne option contre Fort-Ivoire Gonflette et Gigansel Mur de Fer/Malédiction.',3,33),
	 ('Dracolosse','images/pokemon/dracolosse.gif','images/types/dragon.png','images/types/vol.png','wider_longer_gif','images/sprites/sprite-dragonite.png','https://www.smogon.com/dex/sv/pokemon/dragonite/',true,'Dracolosse est un Pokémon utilisé afin de Sweep les équipes adverses après s''être placé avec Danse Draco.',1,12),
	 ('Darkrai','images/pokemon/darkrai.gif','images/types/tenebres.png','images/types/inconnu.png','wider_gif','images/sprites/sprite-darkrai.png','https://www.smogon.com/dex/sv/pokemon/darkrai/',true,'Avec son excellente stat de Vitesse, Darkrai est déjà l''un des Pokémon les plus rapides du jeu. En lui rajoutant le Mouchoir Choix, il devient le meilleur revenge killer de l''OverUsed.',1,20),
	 ('Mite-de-fer','images/pokemon/mite-de-fer.gif','images/types/feu.png','images/types/poison.png','wider_gif','images/sprites/sprite-iron_moth.png','https://www.smogon.com/dex/sv/pokemon/iron-moth/',true,'Mite-de-Fer est souvent joué dans des équipes offensives comme les Hyper Offense du fait de son double type Type Feu Poison retirant passivement les Pics Toxik dès son entrée et offrant des résistances intéressantes tout en ayant un potentiel de Sweep l''équipe adverse.',1,14),
	 ('Pyrobut','images/pokemon/pyrobut.gif','images/types/feu.png','images/types/inconnu.png','longer_gif','images/sprites/sprite-cinderace.png','https://www.smogon.com/dex/sv/pokemon/cinderace/',true,'La particularité de Pyrobut lui vient de son attaque signature Change-Côté qui lui permet de renverser la bataille des Hazards et de dissuader l''adversaire de les poser.',1,19),
	 ('Électhor','images/pokemon/electhor.gif','images/types/electrik.png','images/types/vol.png','wider_gif','images/sprites/sprite-zapdos.png','https://www.smogon.com/dex/sv/pokemon/zapdos/',true,'Electhor est un excellent pivot offensif facile à intégrer dans n''importe quelle équipe car son double type Vol  Électrik et ses bonnes statistiques lui permettent de venir sur Fort-Ivoire à faible prix tout en ayant une chance de le paralyser avec Statik ou le tuer avec Vent Violent.',2,26),
	 ('Heatran','images/pokemon/heatran.gif','images/types/feu.png','images/types/acier.png','wider_gif','images/sprites/sprite-heatran.png','https://www.smogon.com/dex/sv/pokemon/heatran/',true,'Heatran est utile pour sa capacité à piéger et éliminer des Pokémon défensifs et est une bonne arme contre le Stall.',3,36);
INSERT INTO public.pokemon (nom_pokemon_fr,gif,img_type1,img_type2,dimension_gif,sprite,lien,est_ou,description,tier,classement) VALUES
	 ('Chartor','images/pokemon/chartor.gif','images/types/feu.png','images/types/inconnu.png','wider_longer_gif','images/sprites/sprite-torkoal.png','https://www.smogon.com/dex/sv/pokemon/torkoal/',false,NULL,4,NULL),
	 ('Scorvol','images/pokemon/scorvol.gif','images/types/sol.png','images/types/vol.png','wider_gif','images/sprites/sprite-scorvol.png','https://www.smogon.com/dex/sv/pokemon/gliscor/',true,'Scorvol est très apprécié pour sa capacité à stack les Picots tout en empoisonnant les Fort-Ivoire souhaitant les retirer. Le combo Toxik + Séisme menace tous les Pokémon du tier à l''exception de Corvaillus, Airmure et évidemment les autres Scorvol.',1,15),
	 ('Roue-de-fer','images/pokemon/roue-de-fer.gif','images/types/sol.png','images/types/acier.png','wider_gif','images/sprites/sprite-roue-de-fer.png','https://www.smogon.com/dex/sv/pokemon/iron-treads/',true,'La présence de Roue-de-Fer est appréciée dans les équipes basées sur la Pluie ou Hyper Offense du fait de son double type Sol Acier et sa bonne Vitesse lui donnant un intérêt face à Electhor et Gromago.',2,21),
	 ('Forgelina','images/pokemon/forgelina.gif','images/types/fee.png','images/types/acier.png','wider_longer_gif','images/sprites/sprite-tinkaton.png','https://www.smogon.com/dex/sv/pokemon/tinkaton/',false,NULL,4,NULL),
	 ('Rampe-Ailes','images/pokemon/rampe-ailes.gif','images/types/insecte.png','images/types/combat.png','wider_longer_gif','images/sprites/sprite-slither_wing.png','https://www.smogon.com/dex/sv/pokemon/slither-wing/',false,NULL,4,NULL),
	 ('Florizarre','images/pokemon/florizarre.gif','images/types/plante.png','images/types/poison.png','wider_gif','images/sprites/sprite-venusaur.png','https://www.smogon.com/dex/sv/pokemon/venusaur/',false,NULL,4,NULL),
	 ('Oyacata','images/pokemon/oyacata.gif','images/types/eau.png','images/types/inconnu.png','wider_gif','images/sprites/sprite-oyacata.png','https://www.smogon.com/dex/sv/pokemon/dondozo/',true,'Oyacata est un Pokémon utilisé dans des équipes défensives comme les Stall afin de temporiser les Pokémon pouvant se placer grâce à son talent Inconscient.',3,32),
	 ('Mamanbo','images/pokemon/mamanbo.gif','images/types/eau.png','images/types/inconnu.png','wider_longer_gif','images/sprites/sprite-mamanbo.png','https://www.smogon.com/dex/sv/pokemon/alomomola/',true,'Les caractéristiques de HP gargantuesques d''Alomomola, son bon typage défensif et son accès au Régénérateur en font l''un des meilleurs pivots défensifs disponibles. La combinaison de Souhait, Régénérateur et Retournement en fait le meilleur passeur de Souhait de OU, capable de soigner des coéquipiers défensifs sans récupération fiable comme Oyacata et Dinglu',2,29),
	 ('Kyurem','images/pokemon/kyurem.gif','images/types/glace.png','images/types/dragon.png','wider_gif','images/sprites/sprite-kyurem.png','https://www.smogon.com/dex/sv/pokemon/kyurem/',true,'Sa très bonne Attaque Spéciale de 130 et son bulk impressionnant pour un Pokémon offensif sont les principaux atouts de Kyurem. Son double type Dragon Glace est très menaçant sur le plan offensif mais le laisse exposé à de nombreuses faiblesses, notamment les Piège de Roc. Ces faiblesses sont d''ailleurs accentuées par la Vitesse moyenne de Kyurem, qui se situe en dessous des 100 stat de base. L''accès à Lyophilisation est un atout majeur car il permet à Kyurem de passer les types Type EauEau et d''améliorer sa couverture offensive déjà très fournie.',1,17),
	 ('Serpente-Eau','images/pokemon/serpente-eau.gif','images/types/eau.png','images/types/dragon.png','wider_longer_gif','images/sprites/sprite-walking_wake.png','https://www.smogon.com/dex/sv/pokemon/walking-wake/',true,'Serpente-Eau est sans aucun doute le meilleur Pokémon à jouer dans une équipe basée sur le Soleil, bien qu''il puisse également profiter de la pluie grâce à l''effet particulier de sa capacité signature Hydrovapeur.',3,31);
INSERT INTO public.pokemon (nom_pokemon_fr,gif,img_type1,img_type2,dimension_gif,sprite,lien,est_ou,description,tier,classement) VALUES
	 ('Gromago','images/pokemon/gromago.gif','images/types/acier.png','images/types/spectre.png','longer_gif','images/sprites/sprite-gholdengo.png','https://www.smogon.com/dex/sv/pokemon/gholdengo/',true,'Gromago empêche tout moyen de retirer les Hazards à l''adversaire. Ceci grâce à son type Type Spectre l''immunisant à Tour Rapide, son Type Type Acier l''immunisant à Toupie Éclat, et son talent exceptionnel Corps en Or qui bloque l''utilisation d''Anti-Brume et autres attaques de statut (dont Cage Éclair, Tour de Magie, Encore etc...).',0,3),
	 ('Rugit-lune','images/pokemon/rugit-lune.gif','images/types/dragon.png','images/types/tenebres.png','wider_gif','images/sprites/sprite-roaring_moon.png','https://www.smogon.com/dex/sv/pokemon/roaring-moon/',true,'Danse du Dragon Rugit Lune est l''un des sweepers les plus dangereux du Tier grâce à son Attaque et sa Vitesse fantastiques, complétées par une masse décente, un excellent typage à la fois offensif et défensif, et diverses options de couverture qui limitent considérablement sa contre-attaque défensive. Acrobatie, grâce à sa synergie parfaite avec Booster Energy, offre une excellente couverture avec Knock Off en donnant à Roaring Moon une option incroyablement puissante pour frapper super efficacement les menaces comme Great Tusk ainsi que Ogerpon-W, Serperior, et Rillaboom sans avoir besoin de Dragon Dance ; entre elle et Knock Off, Roaring Moon frappe la plupart des joueurs du Tier pour au moins des dégâts neutres, ce qui est souvent suffisant pour nettoyer la fin de la partie.',0,5),
	 ('Lanssorien','images/pokemon/lanssorien.gif','images/types/dragon.png','images/types/spectre.png','wider_longer_gif','images/sprites/sprite-lanssorien.png','https://www.smogon.com/dex/sv/pokemon/dragapult/',true,'Étant l''un des Pokémon les plus rapides du jeu, Lanssorien est un Pokémon très versatile possèdant un double type Type Dragon Spectre résistés par très peu de Pokémon. Ses excellentes statistiques offensives ainsi que son accès à diverses capacités utiles et puissantes font de lui un pokémon imprévisible capable d''être un Wallbreaker, un Pivot offensif, un Sweeper ou un poseur d''écrans si besoin. Son bulk pas si mauvais ainsi que son double type défensivement fait qu''il n''est pas si facile à OHKO sur une attaque neutre et lui offre l''immunité convoitée à la Vitesse Extrême de Dracolosse.',0,8),
	 ('Sorcilence','images/pokemon/sorcilence.gif','images/types/psy.png','images/types/fee.png','longer_gif','images/sprites/sprite-sorcilence.png','https://www.smogon.com/dex/sv/pokemon/hatterene/',true,'Sorcilence est un Pokémon joué pour son talent Miroir Magik et ses statistiques correctes lui permettant à l''aide de son double type initial Psy Fée et la Téracristallisation de devenir un dangereux Sweeper muni de Plénitude et Vampibaiser pour se soigner.',2,28),
	 ('Ogerpon-Masque-du-Puits','images/pokemon/ogerpon-masque_du_puits.gif','images/types/plante.png','images/types/eau.png','wider_longer_gif','images/sprites/sprite-ogerpon-masque-du-puits.png','https://www.smogon.com/dex/sv/pokemon/ogerpon-wellspring/',true,'Cette forme d''Ogerpon se démarque par l''association du type Plante au type Eau qui fait de son attaque signature Massue Liane une puissante attaque de type Eau.',1,11),
	 ('Dinglu','images/pokemon/dinglu.gif','images/types/tenebres.png','images/types/sol.png','wider_longer_gif','images/sprites/sprite-dinglu.png','https://www.smogon.com/dex/sv/pokemon/ting-lu/',true,'Dinglu est un Pokémon utilisé pour son talent Urne du Fléau lui permettant d''encaisser n''importe quelle attaque spéciale neutre de n''importe quel Pokémon à répétition, sinon au moins 1 fois.',1,16),
	 ('Amovénus','images/pokemon/amovenus.gif','images/types/fee.png','images/types/vol.png','longer_gif','images/sprites/sprite-amovenus.png','https://www.smogon.com/dex/sv/pokemon/enamorus/',true,'Grâce à ses très bonne stats offensives et de vitesse, Amovénus est un Pokémon difficilement prévisible, capable d''être aussi bien un puissant Wallbreaker tout comme un Set up Sweeper avec Plénitude. Son double type Type Fée  Vol lui donne des résistances utiles et force de nombreux Pokémon populaires dans le tier notamment de type Sol ou Dragon à devoir s''en aller.',3,34),
	 ('Deoxys-Vitesse','images/pokemon/deoxys-vitesse.gif','images/types/psy.png','images/types/inconnu.png','wider_longer_gif','images/sprites/sprite-deoxys-vitesse.png','https://www.smogon.com/dex/sv/pokemon/deoxys-speed/',true,'La stat exceptionnelle de 180 en Vitesse est bien sûr l''atout majeur de Deoxys Vitesse, l''autorisant à dépasser la plupart des Pokémon même boostés d''un cran. Avec des investissements maximaux, Deoxys-Vitesse est capable de dépasser les Base 100 en Vitesse par exemple.',3,35),
	 ('Zamazenta','images/pokemon/zamazenta.gif','images/types/combat.png','images/types/inconnu.png','wider_longer_gif','images/sprites/sprite-zamazenta.png','https://www.smogon.com/dex/sv/pokemon/zamazenta/',true,'Zamazenta est un Pokémon joué pour sa capacité à empêcher certains Pokémon de Sweep au moins 1 fois grâce à son talent Égide Inflexible et est surtout excellent pour temporiser Scalpereur dans des équipes offensives comme le fait Fort-Ivoire.',0,7),
	 ('Démétéros-Totémique','images/pokemon/demeteros-totemique.gif','images/types/sol.png','images/types/vol.png','wider_longer_gif','images/sprites/sprite-landorus_therian.png','https://www.smogon.com/dex/sv/pokemon/landorus-therian/',true,'Ayant été le roi durant les trois dernières générations, Démétéros-T souffre d''avoir perdu pas mal d''attaques comme Sabotage, Anti-Brume, Toxik, Poliroche ou encore Explosion, ce qui fait qu''il n''est plus aussi versatile qu''avant. Il souffre également de la comparaison avec les nouveaux types Type Sol, notamment Fort-Ivoire qui lui a Sabotage et Tour Rapide.',0,6);
INSERT INTO public.pokemon (nom_pokemon_fr,gif,img_type1,img_type2,dimension_gif,sprite,lien,est_ou,description,tier,classement) VALUES
	 ('Corvaillus','images/pokemon/corvaillus.gif','images/types/acier.png','images/types/vol.png','wider_gif','images/sprites/sprite-corvaillus.png','https://www.smogon.com/dex/sv/pokemon/corviknight/',true,'Corvaillus muni de Demi-Tour est un pivot défensif intéressant grâce à son double type VolAcier l''immunisant à l''empoisonnement et lui permettant de venir sur de nombreux utilisateurs de Séisme comme Fort-Ivoire, Démétéros Totémique et autres attaquants physiques.',1,18),
	 ('Clamiral-Hisui','images/pokemon/clamiral_forme_hisui.gif','images/types/eau.png','images/types/tenebres.png','wider_longer_gif','images/sprites/sprite-samurott_hisui.png','https://www.smogon.com/dex/sv/pokemon/samurott-hisui/',true,'La particularité de Clamiral de Hisui est son accès à Vagues à Lames, une attaque de type Ténèbres boosté par son talent Incisif qui permet de poser les Picots. Clamiral-H peut donc stack hazards tout en infligeant des dégâts aux Pokémon adverses et en ignorant Miroir Magik.',1,13),
	 ('Garde-de-fer','images/pokemon/garde-de-fer.gif','images/types/fee.png','images/types/combat.png','longer_gif','images/sprites/sprite-iron_valiant.png','https://www.smogon.com/dex/sv/pokemon/iron-valiant/',true,'Garde-de-Fer est un des pokémon les plus menaçants du format du fait de sa capacité à dépasser tous ses adversaires à l''aide de l''Energie Booster et consitute un très bon Revenge Killer.',1,10),
	 ('Roigada-de-Galar','images/pokemon/roigada-de-galar.gif','images/types/psy.png','images/types/poison.png','wider_longer_gif','images/sprites/sprite-roigada-de-galar.png','https://www.smogon.com/dex/sv/pokemon/slowking-galar/',true,'Roigada de Galar s''impose comme étant le meilleur pivot défensif du format actuel du fait de son double type Poison Psy et ses statistiques lui permettant de venir sur Amovénus, Garde-de-Fer, et autres attaquants spéciaux comme Electhor.',1,9),
	 ('Chef-de-fer','images/pokemon/chef-de-fer.gif','images/types/acier.png','images/types/psy.png','longer_gif','images/sprites/sprite-chef-de-fer.png','https://www.smogon.com/dex/sv/pokemon/iron-crown/',true,'Chef-de-Fer est un Pokémon qui peut paraître assez moyen au premier abord avec son double type Acier Psy sensible aux attaques Ténèbres comme Sabotage, mais profite comme les autres formes paradoxe de son talent Charge Quantique couplé à l''Energy Booster qui peut augmenter sa vitesse pour dépasser et vaincre les équipes adverses après s''être placé avec Plénitude.',2,22),
	 ('Floréclat','images/pokemon/floreclat.gif','images/types/roche.png','images/types/poison.png','wider_longer_gif','images/sprites/sprite-glimmora.png','https://www.smogon.com/dex/sv/pokemon/glimmora/',true,'Floréclat est un très bon hazard stacker. Il possède les Piège de Roc, les Picots et son talent signature Dépôt Toxique lui permet de déposer des Pics Toxik sur le terrain quand il subit une attaque physique. De plus, Floréclat est le seul Pokémon a apprendre Toupie Éclat, un Tour Rapide qui empoisonne la cible.',2,23),
	 ('Oratoria','images/pokemon/oratoria.gif','images/types/eau.png','images/types/fee.png','wider_longer_gif','images/sprites/sprite-oratoria.png','https://www.smogon.com/dex/sv/pokemon/primarina/',true,'En 9ème génération, Oratoria redevient populaire grâce à un kit assez unique dans le jeu. Son double type Eau Fée est excellent sur le plan défensif et peut se targuer d''une bonne couverture offensive. Avec ses bonnes stats d''Attaque et de Défense Spéciales, Oratoria peut gérer les attaquants spéciaux tout en infligeant de puissants Surf et Pouvoir Lunaire.',2,25),
	 ('Gorythmic','images/pokemon/gorythmic.gif','images/types/plante.png','images/types/inconnu.png','wider_longer_gif','images/sprites/sprite-gorythmic.png','https://www.smogon.com/dex/sv/pokemon/rillaboom/',true,'L''invocation du Champ Herbu grâce à son talent est l''élément central de Gorythmic. Il est, grâce à ce talent, le meilleur utilisateur de Gliss''Herbe, une attaque de Plante qui devient une priorité sous le Champ Herbu. Grâce à sa bonne attaque de base de 125 et le boost du Champ, cette priorité est l''une des plus puissante du jeu.',2,30),
	 ('Gigansel','images/pokemon/gigansel.gif','images/types/roche.png','images/types/inconnu.png','wider_longer_gif','images/sprites/sprite-gigansel.png','https://www.smogon.com/dex/sv/pokemon/garganacl/',true,'Gigansel est utilisé pour son talent exceptionnel faisant de lui une éponge à Statut et offre une résistance intéressante aux attaques de type Spectre.',2,27),
	 ('Sulfura','images/pokemon/sulfura.gif','images/types/feu.png','images/types/vol.png','wider_gif','images/sprites/sprite-sulfura.png','https://www.smogon.com/dex/sv/pokemon/moltres/',true,'Sulfura est un excellent Pokemon défensif, capable de fonctionner comme un mur physique solide et un pivot. Son type et sa capacité lui permettent de punir une multitude d''attaquants physiques du niveau, en menaçant de brûler avec Corps de flamme pour empêcher le pivot depuis U-turn ou en faisant un mur fiable contre les attaquants physiques.',2,24);
